import{S as l,i}from"./assets/vendor-b81b9f86.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const u={formEl:document.querySelector('.js-search-form[data-id="1"]'),imageEl:document.querySelector(".js-image-container")};function m(s){const t="https://pixabay.com/api/",n=`?${new URLSearchParams({key:"42138103-4c7bc70fd41b029843ebe333e",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0})}`,e=t+n;return fetch(e).then(r=>r.json()).catch(r=>{console.error(r)})}const c=document.querySelector(".loader");c.style.display="none";function d(){c.style.display="block"}function f(){c.style.display="none"}function p(s,t=!0){const o=document.querySelector(".js-image-container");t&&(o.innerHTML=""),d(),setTimeout(()=>{const n=s.map(e=>`
      <a href="${e.largeImageURL}" class="lightbox">
        <div class="image-card">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <span>Likes: ${e.likes}</span>
          <span>Views: ${e.views}</span>
          <span>Comments: ${e.comments}</span>
          <span>Downloads: ${e.downloads}</span>
        </div>
      </a>
    `).join("");o.innerHTML=n,f(),h.refresh()},2e3)}const h=new l(".js-image-container  a",{captionsData:"alt",captionDelay:250});u.formEl.addEventListener("submit",s=>{s.preventDefault();const t=s.target.elements.query.value;if(!t){i.error({title:"Помилка",message:"Будь ласка, введіть текст для пошуку"});return}m(t).then(o=>{o.hits.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):p(o.hits)}).catch(o=>{console.error(o),i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})})});
//# sourceMappingURL=commonHelpers2.js.map
